### ISSUE TITLE
Symbolic icons instead of just desaturated icons?

### ISSUE THREAD

**Issue by Leleat** [fthx/simple-task-bar#17]
Currently the extension just desaturates all icons (if the setting is enabled) but still uses the icons of the theme. GNOME uses symbolic icons by default and only falls back to the theme icon if there is no symbolic icon (and desaturates it). GNOME applies it via a css file.

Here is a screenshot. The bottom half shows how it is currently. The top half uses symbolic icons (you can see GNOME's default on the appmenu). 

![Screenshot from 2020-09-29 11-16-42](https://user-images.githubusercontent.com/53054301/94540611-2c521b00-0236-11eb-97d3-51bd8f0ee792.png)

Do you want to add it to your extension or do you want to leave it as is?

**Comment by fthx** [comment]
It's strange. Using Ubuntu 20.04 with Adwaita or Yaru icons, GS does not use symbolic icons.
Here's my GS without Simple Task Bar:
![image](https://user-images.githubusercontent.com/23138504/94543955-f53a3480-024a-11eb-8dea-154537050f95.png)
But I get some symbolic icons for Gnome apps (terminal, files...).

Well, we don't have at the moment any icon in app menu (why do you get one in your screenshots ?) because it's not useful so there's no appearance homogeneity issue. But maybe we can let the user choose what he wants to do, if the needed code is not too heavy ?

**Comment by Leleat** [comment]
> (why do you get one in your screenshots ?) 

I enabled them just for the screenshot.

It's about 10 lines of code.

**Comment by Leleat** [comment]
GNOME applies the 'app-menu-icon' style here:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/panel.js#L216

and in the ccs file they apply the symbolic icons
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/data/theme/gnome-shell-sass/widgets/_panel.scss#L67

**Comment by fthx** [comment]
Did you check appearance of the task bar icons side-by-side when some are symbolic and other not?
If this point is ok, your PR is welcome!

**Comment by Leleat** [comment]
In my screenshot the VSCode icons is not symbolic (only Firefox and Files are). I can open a PR and you can test it yourself since I don't know why your firefox icon isn't symbolic. Maybe Ubuntu changes it? I am using Fedora, which is pretty vanilla GNOME.

**Comment by fthx** [comment]
Ok for a test. My Firefox is a snap, maybe this explains the classic icon.
